### ISSUE TITLE
error compile smart_bathroom_project

### ISSUE THREAD

**Issue by SvetlanaFaina** [sorykkk/iot-bootcamp-2020-team-project#1]
Need to add to the project library file <LiquidCrystal_I2C.h>
Otherwise the project are not compile.

![screen](https://user-images.githubusercontent.com/65874583/86880823-efbec980-c0f5-11ea-92ab-93c132fe7462.jpg)

**Comment by sorykkk** [comment]
"Need to add to the project library file <LiquidCrystal_I2C.h>
Otherwise the project are not compile."

so add it by downloading in arduino ide library manager :)
